# Generated by Django 4.2.1 on 2023-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
