# Generated by Django 4.2.1 on 2023-05-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_name', models.CharField(max_length=50, verbose_name='Autor name')),
                ('autor_description', models.TextField(blank=True, null=True, verbose_name='Autor description')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='Genre')),
                ('genre_description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_house_name', models.CharField(max_length=50, verbose_name='Publishing house name')),
                ('publishing_house_description', models.TextField(blank=True, null=True, verbose_name='Publishing house description')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100, verbose_name='Series')),
                ('series_description', models.TextField(blank=True, null=True, verbose_name="Count book's series")),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='Book name')),
                ('book_image', models.ImageField(blank=True, upload_to='book')),
                ('book_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('year_publishing', models.DateField(max_length=50, verbose_name='Year publishing book')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.autor', verbose_name='autor')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.genre', verbose_name='genre')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directories.series', verbose_name='series')),
            ],
        ),
    ]
