# Generated by Django 4.2.1 on 2023-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='/book/book-default.jpg', upload_to='book/'),
        ),
    ]
