# Generated by Django 4.2.1 on 2023-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=1, max_length=400, verbose_name='description'),
            preserve_default=False,
        ),
    ]
