# Generated by Django 4.2.1 on 2023-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(choices=[('Solid', 'solid'), ('Soft', 'soft'), ('Absent', 'absent')], default=1, max_length=6, verbose_name='Binding book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='format_book',
            field=models.CharField(choices=[('Super small', '84x108/64'), ('Small', '75x90/32'), ('Standart', '60x90/16'), ('Bigger', '70x108/16'), ('Big', '60x90/8'), ('Super big', '84x108/8')], default=1, max_length=12, verbose_name='Book format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
