# Generated by Django 4.2.1 on 2023-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_book_binding_book_format_book_book_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default=1, max_length=25, verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
