# Generated by Django 4.2.1 on 2023-06-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_alter_book_autor_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='/book/book-default.jpg', upload_to='book/%Y/%m/%d/'),
        ),
    ]
