# Generated by Django 4.2.1 on 2023-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Age restrictions'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Book weight(gramme)'),
        ),
    ]
