# Generated by Django 4.2.1 on 2023-06-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format_book',
            field=models.CharField(choices=[('84x108/64', '84x108/64'), ('75x90/32', '75x90/32'), ('60x90/16', '60x90/16'), ('70x108/16', '70x108/16'), ('60x90/8', '60x90/8'), ('84x108/8', '84x108/8')], max_length=12, verbose_name='Book format'),
        ),
    ]
