# Generated by Django 4.2.1 on 2023-05-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_book_age_restrictions_book_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.CharField(choices=[('Y', 'active'), ('N', 'inactive')], default=1, max_length=4, verbose_name='Book active'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='counter_book',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Count of books available'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='directories.publishing_house', verbose_name='Publishing house'),
            preserve_default=False,
        ),
    ]
