# Generated by Django 4.2.1 on 2023-06-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_alter_book_format_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=6),
        ),
    ]
