# Generated by Django 4.2.1 on 2023-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_book_active_book_counter_book_book_publishing_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Rating'),
        ),
    ]
