# Generated by Django 4.2.1 on 2023-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_bookincart_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='staff.bookincart'),
        ),
    ]
