# Generated by Django 4.2.1 on 2023-06-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(blank=True, to='staff.bookincart'),
        ),
    ]
